### PR TITLE
Update hu.tsx

### PR DESCRIPTION
**Pull request by debyos**
Here is the rest.
A question: where can I find "display" on the front-end side?
Thanks
Gábor

### CODE REVIEW

**Comment by zdila** [comment]
Which _display_? Please send a screenshot.

**Comment by debyos** [comment]
> 
> 
> Which _display_? Please send a screenshot.

Actually, that is also my question: [in line 79 there is a 'Display'](https://github.com/FreemapSlovakia/freemap-v3-react/blob/develop/src/translations/en.tsx) but I can't find it on freemap.sk

**Comment by zdila** [comment]
It is under _Live tracking_:

image

**Comment by debyos** [comment]
Great, thank you!

**Pull request merged**
