### PR TITLE
Create osmTagToNameMapping-it.ts

### PR DESCRIPTION
**Pull request by dp7x**
Second file to translate into italian

### CODE REVIEW

**Comment by zdila** [comment]
@dp7x please write me here if you are done with this pull request. Thank you!

**Comment by dp7x** [comment]
Hello Martin
Yes, the pull request for the translation is complete !

Please let me know how i can review and correct the translation after it is online .

Thank you!!

Diego Perucci

Il giorno 9 mag 2022, alle ore 07:49, Martin Ždila ***@***.***> ha scritto:

﻿

@dp7x<https://github.com/dp7x> please write me here if you are done with this pull request. Thank you!

**Comment by zdila** [comment]
@dp7x thanks, you can check it now.

Also if you can then please translate the following (you can do it as a comment here):
```javascript
errorHtml:
      '<h1>Problem starting application</h1>' +
      '<p>Please make sure you are using recent version of a modern browser (Google Chrome, Firefox, Safari, Opera, Edge, Chromium, Vivaldi, Brave, …).</p>',
    nojsMessage:
      'JavaScript enabled browser is required to run this application.',
    loadingMessage: 'Loading…',
```

also:
```
      <h1>Application error</h1>
      <p>Ticket ID: ${id}.</p>
      <p>You can send ticket ID and steps how to reproduce the error to <a href="mailto:freemap@freemap.sk">freemap@freemap.sk</a>.</p>
```

...and two more files:

- `src/components/supportUsModal/translations/en.tsx`
- `src/translations/en-shared.json`

And finally, in the different project https://github.com/FreemapSlovakia/freemap-mapnik/blob/develop/legend.js:

- add `it: '...'` below every `en: '...'`
- also add IT translation as next parameter in lines like `road('path', 'trail is mostly visible', 'trasa je väčšinou viditeľná', false, 2),` -> `road('path', 'trail is mostly visible', 'trasa je väčšinou viditeľná', '...italian translation...', false, 2),` (there are many such lines, also with `poi(...`, `landcover(...` and maybe more. I will fix accidental syntax errors.

Thanks!

(PS: feel free to provide your name which should we put to the planned "credits" dialog)

**Comment by dp7x** [comment]
errorHtml:
      '<h1>Problema nell''avvio dell''applicazione</h1>' +
      '<p>Per favore assicurati di utilizzare una versione recente di un browser moderno (Google Chrome, Firefox, Safari, Opera, Edge, Chromium, Vivaldi, Brave, …).</p>',
    nojsMessage:
      'E'' richiesto un browser con JavaScript abilitato per avviare questa applicazione.',
    loadingMessage: 'Caricamento…',

**Comment by dp7x** [comment]
Please note: I used double '' but I don't know if it is needed in the code.
Just one ' is needed in the translation.
For example: 
_Errore dell**'**applicazione_
is the correct translation

**Comment by dp7x** [comment]
Ok, I created 2 pull requests for :

    src/components/supportUsModal/translations/en.tsx
    src/translations/en-shared.json

and started working on 
    https://github.com/FreemapSlovakia/freemap-mapnik/blob/develop/legend.js:

Check them and let me know.
About the "credits" dialog, I appreciate it very much and will write to you in private.
Thank you !

**Comment by dp7x** [comment]
Hello Martin
the translation of LEGEND.JS is (finally...) complete !
Please check the code to see if there are any errors.

thank you !

**Pull request merged**
