### PR TITLE
Create it.tsx

### PR DESCRIPTION
**Pull request by dp7x**
I am working on the italian translations of freemap.
Please note the translation of this file is still not complete !

### CODE REVIEW

**Comment by zdila** [comment]
@dp7x ok thank you! note that you don't need to translate commented lines (starting with `//`)

**Comment by dp7x** [comment]
Thank you @zdila , I knew but it was easy anyway so I did it ! :)

Please help me with pieces of code like this: what are the parts I have to translate ?

        // eslint-disable-next-line
        short: ({ arrivo, prezzo, numeri }) => (
          <>
            Arrival: <b>{arrival}</b> | Price: <b>{price} €</b> | Lines:{' '}
            {numbers?.map((n, i) => (
              <Fragment key={n}>
                {i > 0 ? ', ' : ''}
                <b>{n}</b>
              </Fragment>
            ))}
          </>
        ),

Thanx  !

**Comment by zdila** [comment]
Translate only this line omitting words in `{}`:
```
Arrival: <b>{arrival}</b> | Price: <b>{price} €</b> | Lines:{' '}
```

**Comment by zdila** [comment]
Thanks you, I've merged the pull request, but feel free to do another one if you want to update the file.

**Pull request merged**
